# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alex Ordiner
title: tecnico audio video
email: ordiner@gmail.com
website: ordiner.github.io/cv/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: su di me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Ciao, mi chiamo Alex e sono un tecnico audio-video.
 
 Conclusi gli studi superiori *(perito elettronico)*, e parallelamente alla formazione universitaria *(tecnologie multimediali)*, ho iniziato la mia esperienza lavorativa come tecnico per eventi di piccole e medie dimensioni. 
 
 Ho poi continuato a lavorare a tempo pieno come tecnico audiovisivo occupandomi, nel tempo, di vari aspetti di questa professione.
 
 Con le esperienze lavorative, e continuando a sperimentare con progetti personali, ho ampliato progressivamente le mie competenze tecniche - che attualmente credo di poterle raggruppare in tre aree: 
 
 <mark>eventi live</mark> --- <mark>post-produzione</mark> --- <mark>integrazione di sistemi</mark>

content:
  - title: sulle mie competenze # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: eventi live
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Il mondo di congressi, eventi aziendali, spettacoli. Il mondo, appunto, delle cose "dal vivo".
        description: | # this will include new lines to allow paragraphs
          Mi sono occupato, e mi occupo tutt'ora, dell'ideazione completa e della gestione della regia tecnica di eventi di piccole e medie dimensioni (2000+ persone di pubblico). Per eventi più grandi ho coperto ruoli specifici.

          Oltre la scelta delle attrezzature, il coordinamento dell'installazione, il cablaggio, e tutto quello che riguarda l'allestimento; mi sono anche occupato del coordinamento della squadra di tecnici.
          
          Giusto per fare qualche nome, lavoro abitualemnte con Midas Pro, Behringer X32-wing, BMD Atem contellation e mini extreame, Sony e Panasonic camcorder e PTZ, Bitfocus Companion, Wirecast, OBS, vMix, Dante, NDI,...

              
      - layout: top-middle
        title: post-produzione
        quote: >
          tutto il lavoro che arriva "dopo", per consegnare un prodotto .
        description: | # this will include new lines to allow paragraphs
         Mi sono occupato di montaggio audiovisivo di vario tipo, legato al mondo congressuale e dello spettacolo.

         I lavori principali hanno riguardato montaggi video multicamera di concerti, congressi, videodidattici, realizzazione di video formativi per il personale, e creazione di video di presentazione prodotti.

         Parallelamente collaboro alla produzione tecnica, registrazione e montaggio di podcast.

         Alcuni dei software di post-produzione utilizzati:

         Apple Final Cut  *(Apple Certified Professional per Final Cut Pro X e Motion - 2013 presso Espero)*, DaVinci Resolve, 
         Affinity Suite, 
         Hindenburg Pro, Cavalry 2D, Canva, 
         postprocesso audio con DxRevive-IkMultimedia-iZotope,…
         
         
      - layout: top-middle
        title: integrazione di sistemi
        quote: >
          avete presente quando schicci un tasto e tutta la sala riunione si accende? Ecco, quella cosa lì.
        description: | # this will include new lines to allow paragraphs
         Per concludere, una parte della mia esperienza lavorativa riguarda l'installazione di sistemi multimediali per sistemi fissi in teatri, auditorium, sale conferenze, aule universitarie,…

         Tali sistemi includono proiettori, schermi motorizzati, ledwall, monitor di varie dimensioni, microfonia, sistemi di videoconfernza, videocamere controllate, luci,…

         Oltre alla progettazione, alla selezione delle apparecchiature e alla loro installazione, mi occupo prevalentemente della programmazione dei sistemi.
         Protocolli di comunicazione, creazione delle interfacce utente, adatammento degli impianti secondo le esigenze del cliente, etc.

         Per i progetti più complessi ho utilizzato Kramer (Kramer Control System Designer certificato), Extron (certificato) e Q-sys (in fase di certificazione)
         
  - title: competenze trasversali # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: right
        title: ambito tecnico
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - conoscenza approfondita di sistemi informatici MacOS/Win e conoscenza base sistemi Linux
            - discreta conoscenza delle infrastrutture di reti dati, con particolare attenzione all'AV over IP
            - buona conoscenza di formati multimediali: codec audio-video-immagine e le loro caratteristiche
            - buona competenza nella ripresa video e sonora con fotocamere, camcorder, registratori esterni e simili - nozioni di illuminazione professionale
            - competenza base della sonorizzazione degli ambienti
            
      - layout: left
        title: ambito personale
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
           Ho sempre lavorato in ambienti collaborativi, dove il confronto con i colleghi è fondamentale per la riuscita del servizio.

           Ho maturato esperienza nel lavoro con i giovani, avendo gestito in passato campeggi estivi per ragazzi delle scuole medie e superiori.
           Sempre come attività legata al mondo giovanile, ho cogestito per 2 anni le sale prove di un centro di aggregazione giovanile.

           Da diversi anni partecipo come volontario a vari festival di divulgazione gestendo, oltre alla parte tecnica, il coordinamento di volontari - per lo più giovani
           Recentemente, ho insegnato tecniche di videoproiezione per un ente di formazione, lavorando con classi di neodiplomati. 
           Questa esperienza mi ha permesso di sviluppare esperienza nel coordinare giovani in contesti formativi, portando con me un approccio pratico e di condivisione delle competenze.

  - title: formazione scolastica # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: I.S.I.S. Malignani di Udine
        caption: 2000
        sub_title: Perito Industriale in Elettronica e Telecomunicazioni
        quote: >
          quote
        description: | # this will include new lines to allow paragraphs
          description

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      punto elenco:
      - prova punto elenco

      Se vuoi, è anche possibile scaricare un mio curriculum un po' più formale - [Ordiner Alex CV](/cv/images/Ordiner Alex - curriculum tecnico 2025.pdf)
    

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag