# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alex Ordiner
title: tecnico audio video
email: ordiner@gmail.com
website: ordiner.github.io/cv/

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: su di me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Ciao, mi chiamo Alex e sono un tecnico audio-video che vive in **Friuli**.
 
 Conclusi gli studi superiori *(perito elettronico)* e parallelamente alla formazione universitaria *(tecnologie multimediali)*, ho iniziato la mia esperienza lavorativa come tecnico per eventi di piccole e medie dimensioni. 
 
 Negli anni ho continuato a lavorare a tempo pieno come tecnico audiovisivo occupandomi di vari aspetti di questa professione.
 
 Grazie alle esperienze lavorative, e continuando a sperimentare con progetti personali, ho ampliato progressivamente le mie competenze tecniche - che attualmente credo di poterle raggruppare in tre aree: 
 
 <mark>eventi live</mark> --- <mark>post-produzione</mark> --- <mark>integrazione di sistemi</mark>

content:
  - title: sulle mie competenze professionali # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: eventi live
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Il mondo di congressi, eventi aziendali, spettacoli. Il mondo, appunto, delle cose "dal vivo"
        description: | # this will include new lines to allow paragraphs
          La mia esperienza è iniziata seguendo il palco dei piccoli concerti, e si è velocemente contaminata con l’ambito video. Da lì ho cominciato a lavorare in **conferenze, eventi aziendali, concerti e spettacoli di vario tipo**.

            Mi sono occupato, e mi occupo tutt’ora, dell’ideazione completa e della gestione della regia tecnica per eventi di piccole e medie dimensioni (1000+ persone di pubblico).
            **Gestione audio, regia video, contributi e streaming** sono gli ambiti in cui metto più spesso mano.
            
            Per eventi più grandi ho ricoperto ruoli tecnici specifici all’interno del team.
            
            Oltre alla scelta e configurazione delle attrezzature, mi occupo anche del coordinamento dell’installazione, del cablaggio e, in generale, di tutto quello che riguarda l’allestimento tecnico. Mi capita anche di **gestire le squadre di tecnici**.
            
            Giusto per fare qualche nome di attrezzatura, lavoro abitualmente con:
            *Midas PRO, Behringer X32/Wing, BMD ATEM Constellation e Mini Extreme, camcorder e PTZ broadcast Sony e Panasonic, Bitfocus Companion, d&b audiotechnik, Wirecast, OBS, vMix, Dante, NDI…*


              
      - layout: top-middle
        title: post-produzione
        quote: >
          tutto il lavoro, dietro al computer, per creare i contenuti multimediali.
        description: | # this will include new lines to allow paragraphs
         L'interesse per il video unito al mondo degli eventi live, mi ha naturalmente portato ad occuparmi di montaggi legati al mondo congressuale e dello spettacolo.
         Per esempio: **sistemazione e allineamento di riprese congressuali, editing multicamera di concerti, video didattici per il personale aziendale.**
         All'editing ho affiancato competenze base di grafica ed animazione 2D 

         Negli ultimi anni mi sono infine interessato alla produzione tecnica, registrazione e montaggio di **podcast** .

         Anche in questo caso, volendo fare qualche nome:
         *Apple Final Cut & Motion  *(Apple Certified)*, DaVinci Resolve, Affinity Suite, Hindenburg Pro, Cavalry 2D, Canva, 
         post-processo audio con DxRevive - iZotope RX,...*
         
         
      - layout: top-middle
        title: integrazione di sistemi
        quote: >
          premi un tasto e tutta la sala riunione si accende? Ecco, quella cosa lì.
        description: | # this will include new lines to allow paragraphs
            Una parte della mia esperienza riguarda l’installazione e l’integrazione di sistemi multimediali in impianti fissi di teatri, auditorium, sale conferenze, aule universitarie e simili.

            Si tratta di proiettori, schermi, ledwall, monitor, microfoni, videoconferenza, videocamere, luci e molto altro.

            Oltre all’installazione vera e propria delle apparecchiature, mi occupo soprattutto della programmazione dei sistemi di controllo: protocolli di comunicazione, creazione delle interfacce utente, adattamento degli impianti secondo le esigenze del cliente.

            Per i progetti più complessi ho lavorato con Q-Sys *(in fase di certificazione)*, Kramer *(certificato)* e Extron *(certificato)*, e con apparecchiature come: Shure serie MXA, proiettori 26k, ledwall,...
            
            
  - title: sulle altre cose che ho imparato # Title for the section
    layout: list # Type of content section (list/text)
    content:
#      - layout: right
#        title: ambito tecnico
#        # link: boringcompany.com
#        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#        description: | # this will include new lines to allow paragraphs
#            - conoscenza approfondita di sistemi informatici MacOS/Win e conoscenza base sistemi Linux
#            - discreta conoscenza delle infrastrutture di reti dati, con particolare attenzione all'AV over IP
#            - buona conoscenza di formati multimediali: codec audio-video-immagine e le loro caratteristiche
#            - buona competenza nella ripresa video e sonora con fotocamere, camcorder, registratori esterni e simili - nozioni di illuminazione professionale
#            - competenza base della sonorizzazione degli ambienti
            
      - layout: right
        title: insegnamento
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: ovvero provare a trasmettere delle competenze
       # quote: >
        #  quello che non c'entra con la tecnica
        description: | # this will include new lines to allow paragraphs
           Ho maturato esperienza nel lavoro con i giovani, avendo gestito in passato campeggi estivi per ragazzi delle scuole medie e superiori.
           Sempre come attività legata al mondo giovanile, ho cogestito per 2 anni le sale prove di un centro di aggregazione giovanile.

           Da diversi anni partecipo come volontario a vari festival di divulgazione gestendo, oltre alla parte tecnica, il coordinamento di volontari - per lo più giovani.
           Recentemente, ho insegnato tecniche di videoproiezione e videomapping per un ente di formazione, lavorando con classi di neodiplomati. 
           
           Queste ed altre attività mi hanno permesso di sviluppare esperienza nel coordinare ragazzi e persone motivate ad imparare in contesti formativi, portando con me un approccio pratico e di condivisione delle competenze.            

  - title: e su quelle che sto imparando # Title for the section 
    layout: list # Type of content section (list/text)
    content:             
      - layout: left
        title: idee per il futuro
        # link: boringcompany.com
        # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        caption: ovvero sul come cercare di non fermarsi mai
        quote: >
          “Be curious. Read widely. Try new things. What people call intelligence just boils down to curiosity.” — Aaron Swartz
        description: | # this will include new lines to allow paragraphs
           Le tecnologie e le loro applicazioni mi hanno sempre affascinato, e probabilmente continueranno a farlo in futuro.
           Oltre all'aspetto tecnico però sono curioso sugli aspetti di come tali tecnologie impattino ed impatteranno sulla nostra società.
           
           Sto inoltre trovando sempre più interessante indagare e sperimentare l'impatto delle tecnologie sulla trasmissione del sapere e della conoscenza.
           Mi sto infatti avvicinando sempre di più all'aspetto ideativo dei prodotti multimediali.
           Per far sì che la tecnica diventi non solo fine a sé stessa, ma lo strumento per il passaggio di un messaggio.
           
           Infine, ma non per importanza, mi piacerebbe restituire alla comunità e a chi ha voglia di imparare, un po' delle conoscenze che ho maturato negli anni. Senza presunzione di essere il detentore di qualche genere di verità, ma la sola espressione della volontà di trasmissione di una personale esperienza.

  - title: formazione scolastica # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Perito Industriale in Elettronica e Telecomunicazioni
        caption: 2000
        sub_title: diploma
        quote: >
          ITI A. Malignani di Udine
       # description: | # this will include new lines to allow paragraphs
       #   description
          
      - layout: top-middle
        title: Tecnologo della comunicazione audiovisiva e multimediale
        caption: 2007
        sub_title: laurea
        quote: >
          Università degli studi di Ferrara
       # description: | # this will include new lines to allow paragraphs
       #   description

  - title: per concludere
    layout: text
    content: | # this will include new lines to allow paragraphs

      Se vuoi è possibile scaricare un mio curriculum, un po' più compatto e formale: [Ordiner Alex CV](/cv/images/Ordiner Alex - curriculum tecnico 2025.pdf)
    

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag